package kh.bank.dgb.ibs.cbs.model

import java.math.BigDecimal

/**
 * Port of `CommonBody` (bizmob.corpbanking.ebanking.model) — the "표준전문헤더부·공통부" (standard
 * message common section) of the Maru core-banking protocol. All ~90 fields kept, matching the
 * old app exactly, even though only a handful (see `MaruMessageFactory`) are ever actually set —
 * this is CBS's own wire contract, not ours to trim. Includes the full manager-approval
 * (책임자승인) workflow fields across 4 levels and multi-currency teller cash amounts, none of
 * which this rewrite's scope currently exercises.
 */
data class CommonBody(
	var ctryCd: String = "",
	var compIdCd: String = "",
	var svcID: String = "",
	var procResRecSvcID: String = "",
	var ifID: String = "",
	var trxSyncTypeCd: String = "",
	var inExTypeCd: String = "",
	var exInstCd: String = "",
	var sysEnvTypeCd: String = "",
	var trxProcTypeCd: String = "",
	var orgTrxRestYN: String = "",
	var orgTrxScnID: String = "",
	var orgTrxGUID: String = "",
	var bankCd: String = "",
	var trxBrchCd: String = "",
	var outBrchTypeCd: String = "",
	var actTrxBrchCd: String = "",
	var trmnInstBrchCd: String = "",
	var chnTypeCd: String = "",
	var chnDetTypeCd: String = "",
	var trmnTypeCd: String = "",
	var trmnNo: String = "",
	var scnID: String = "",
	var scnFileNm: String = "",
	var scnFileVer: String = "",
	var langTypeCd: String = "",
	var terminalUniqueNo: String = "",
	var mgrApprProcStatusCd: String = "",
	var lastMgrLvl: String = "",
	var mgrApprSeqNo: Long = 0L,
	var mgrApprTypeCd: String = "",
	var mgrApprReqReason: String = "",
	var mgrEmpNoLvl1: String = "",
	var dsgtApprChngYNLvl1: String = "",
	var chngDsgtApprEmpNoLvl1: String = "",
	var mgrApprReasonLvl1: String = "",
	var mgrEmpNoLvl2: String = "",
	var dsgtApprChngYNLvl2: String = "",
	var chngDsgtApprEmpNoLvl2: String = "",
	var mgrApprReasonLvl2: String = "",
	var mgrEmpNoLvl3: String = "",
	var dsgtApprChngYNLvl3: String = "",
	var chngDsgtApprEmpNoLvl3: String = "",
	var mgrApprReasonLvl3: String = "",
	var mgrEmpNoLvl4: String = "",
	var dsgtApprChngYNLvl4: String = "",
	var chngDsgtApprEmpNoLvl4: String = "",
	var mgrApprReasonLvl4: String = "",
	var lastMgrEmpNo: String = "",
	var lastMgrAlternativeApprYN: String = "",
	var dsgtApprChngYNLast: String = "",
	var lastChngDsgtApprEmpNo: String = "",
	var lastMgrApprReason: String = "",
	var bizDate: String = "",
	var acctProcYN: String = "",
	var inqUpdTypeCd: String = "",
	var atmClsTypeCd: String = "",
	var tellerID: String = "",
	var asstTellerID: String = "",
	var custIDTypeCd: String = "",
	var custID: String = "",
	var perIDCardImgNo: String = "",
	var abcTrxDetTypeCd: String = "",
	var custNm: String = "",
	var custInfoMaskYN: String = "",
	var tellerCashBalApplyYN: String = "",
	var slipTrxYN: String = "",
	var slipNo: String = "",
	var tellerSlipSeqNo: Long = 0L,
	var tellerUsdCashAmt: BigDecimal = BigDecimal.ZERO,
	var tellerUsdOthBankAmt: BigDecimal = BigDecimal.ZERO,
	var tellerUsdAltTrnsAmt: BigDecimal = BigDecimal.ZERO,
	var tellerKhrCashAmt: BigDecimal = BigDecimal.ZERO,
	var tellerKhrOthBankAmt: BigDecimal = BigDecimal.ZERO,
	var tellerKhrAltTrnsAmt: BigDecimal = BigDecimal.ZERO,
	var tellerEurCashAmt: BigDecimal = BigDecimal.ZERO,
	var tellerEurOthBankAmt: BigDecimal = BigDecimal.ZERO,
	var tellerEurAltTrnsAmt: BigDecimal = BigDecimal.ZERO,
	var loginTypeCd: String = "",
	var procLoginTypeCd: String = "",
	var trxDateExtYN: String = "",
	var trxDate: String = "",
	var trxTime: String = "",
	var sysDate: String = "",
	var sysTime: String = "",
	var msgReqDate: String = "",
	var msgReqTime: String = "",
	var msgContYN: String = "",
	var msgRespDate: String = "",
	var msgRespTime: String = "",
	var msgProcResTypeCd: String = "",
	var outMsgTypeCd: String = "",
	var massOutSuspYN: String = "",
	var msgContSeqNo: String = "",
	var errCd: String = "",
	var errSysCd: String = "",
)
