-- Reconstructed from the old app's MyBatis mapper XML (BIZMOB_HOME/ibs/conf/mybatis/mapper/*.xml)
-- and the matching Java DTO classes (src/main/java/bizmob/corpbanking/dto/*.java), since no DDL
-- exists anywhere in the old repo and no schema dump was available from the real DB.
--
-- This reconstructs every table/column actually referenced by the 10 DAOs — nothing more. It is
-- a best-effort guess at types/lengths from how each column is used, NOT verified against the
-- real production schema. In particular:
--   - No indexes or foreign keys, per instruction — primary keys only, where a query's WHERE/
--     UPDATE clause makes the key column unambiguous.
--   - VARCHAR lengths are guesses; widen freely if real data doesn't fit.
--   - Column types for SERVICE_STATUS's *_time/*_date fields follow the old DTO's declared Java
--     type (String), not what the name implies (they're VARCHAR here, not TIME/TIMESTAMP).
-- Reconcile against a real schema dump before this ever points at anything but local dev/CI.

CREATE TABLE bbs_category (
	category_code varchar(20) PRIMARY KEY,
	category_id integer,
	category_name varchar(200),
	category_name_kh varchar(200),
	parent_category_code varchar(20)
);

CREATE TABLE bbs_board (
	board_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	category_code varchar(20),
	board_title_en varchar(500),
	board_title_kh varchar(500),
	board_html_en text,
	board_html_kh text,
	board_view_count integer DEFAULT 0,
	created_date timestamp,
	is_deleted smallint DEFAULT 0
);

CREATE TABLE bbs_board_attach (
	attach_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	board_id integer,
	attach_name varchar(255),
	attach_original_name varchar(255),
	attach_ext varchar(20),
	attach_size double precision,
	attach_content_type varchar(100),
	attach_data bytea,
	created_by varchar(50),
	created_date timestamp,
	is_deleted smallint DEFAULT 0,
	deleted_by varchar(50),
	deleted_date timestamp
);

CREATE TABLE bbs_board_product (
	board_id integer PRIMARY KEY,
	product_code varchar(50),
	product_name_en varchar(255),
	product_name_kh varchar(255),
	product_desc_en text,
	product_desc_kh text,
	product_interest_rate varchar(50)
);

CREATE TABLE bbs_board_newsevent (
	board_id integer PRIMARY KEY,
	is_banner_display smallint DEFAULT 0
);

CREATE TABLE prepare_document (
	code varchar(50) PRIMARY KEY,
	parent_code varchar(50),
	item varchar(500)
);

CREATE TABLE purpose_of_transfer (
	code varchar(50) PRIMARY KEY,
	parent_code varchar(50),
	item varchar(500),
	item1 varchar(500)
);

CREATE TABLE remark_document (
	code varchar(50) PRIMARY KEY,
	parent_code varchar(50),
	item varchar(500)
);

CREATE TABLE resource_file_info (
	res_file_id varchar(50) PRIMARY KEY,
	res_file_type_code varchar(20),
	res_file_name varchar(255),
	res_file_ext varchar(20),
	res_file_content_type varchar(100),
	res_file_size bigint,
	res_file_data bytea,
	created_by varchar(50),
	created_date timestamp,
	updated_by varchar(50),
	updated_date timestamp
);

CREATE TABLE service_status (
	service_status_type_code varchar(20) PRIMARY KEY,
	service_status_code varchar(20),
	service_status_from_time varchar(20),
	service_status_to_time varchar(20),
	service_status_description varchar(500),
	updated_by varchar(50),
	updated_date varchar(50)
);

CREATE TABLE visited_notify (
	userid varchar(50) PRIMARY KEY,
	visityn varchar(1),
	visitdate varchar(8),
	visittime varchar(9)
);
